config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from proyecto_final.blog.view import ListBlogPage, DetailBlogPage

urlpatterns = [
    #path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    #path(
    #     "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    #path("users/", include("proyecto_final.users.urls", namespace="users")),
    #path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", TemplateView.as_view(template_name="blog/home.html"), name="home"),
    path("aboutus", TemplateView.as_view(template_name="blog/aboutus.html"), name="aboutus"),
    path("pages", ListBlogPage.as_view(), name="pages"),
    path("pages/<int:pk>", DetailBlogPage.as_view(), name="page-detail"),
    path("pages/", include("proyecto_final.blog.urls", namespace="pages")),
    path("accounts/", include("proyecto_final.accounts.urls", namespace="accounts")),
    path("messages/", include("proyecto_final.messages_blog.urls", namespace="messages")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

proyecto_final/accounts/urls.py
from django.urls import path
from proyecto_final.accounts.view import LoginView, RegisterView, ChangePassword, EditProfile, ProfileCreateUpdateView, ProfileView
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView


app_name = "accounts"
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(template_name= "blog/home.html"), name="logout"),
    path("signup/", RegisterView.as_view(), name="singup"),
    path("password/", ChangePassword.as_view(), name="change_password"),
    path("edit_profile/", EditProfile.as_view(), name="edit_profile"),
    path("edit_avatar/", ProfileCreateUpdateView.as_view(), name="edit_avatar"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

proyecto_final/blog/urls.py
from django.urls import path
from proyecto_final.blog.view import CreateBlogPage, UpdateBlogPage, DeleteBlogPage


app_name = "pages"
urlpatterns = [
    path("create/", CreateBlogPage.as_view() , name="create"),
    path("edit/<int:pk>", UpdateBlogPage.as_view(), name="edit"),
    path("delete/<int:pk>", DeleteBlogPage.as_view(), name="delete"),
]

proyecto_final/users/urls.py
from django.urls import path

from proyecto_final.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

proyecto_final/accounts/models.py
from django.db import models
from proyecto_final.users.models import User


class Profile(models.Model):
    user = models.ForeignKey(User ,on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    link = models.CharField(max_length=255, blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to="images/profile")

proyecto_final/blog/models.py
from django.db import models
from proyecto_final.users.models import User
from datetime import datetime, date
from ckeditor.fields import RichTextField

#python manage.py collectstatic para que poder usar el ckeditor luego de instalarlo con pip

class BlogPage(models.Model):
    title = models.CharField(max_length=200)
    caption = models.CharField(max_length=200, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    author = models.ForeignKey(User ,on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    page_date = models.DateField(auto_now_add=True)

    

proyecto_final/messages_blog/models.py
from django.db import models

class Message(models.Model):
    from_message = models.CharField(max_length=50)
    to = models.CharField(max_length=50)
    message = models.CharField(max_length=400)
    

proyecto_final/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Proyecto Final.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = CharField(_("First Name"), blank=True, max_length=255)
    last_name = CharField(_("Last Name"), blank=True, max_length=255)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

proyecto_final/accounts/forms.py
from attr import field
from django import forms
from proyecto_final.users.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from proyecto_final.accounts.models import Profile
from django.db import models


class ProfileForms(forms.Form):
    bio = forms.CharField(required=False)
    link = forms.CharField(required=False)
    profile_image = forms.ImageField(allow_empty_file=True)

    class Meta:
        model = Profile
        fields = ('bio', 'link','profile_image')

#modifique la class Meta en forms.py de django.contrib linea 98 agrego campo email y en la clase UserCreationFormCustom agreo el campo para que guarde el dato
class UserCreationFormCustom(UserCreationForm):
    
    def save(self, commit: bool = True) -> User:
        print(self.__dict__)
        user = User.objects.create(
            username =  self.data['username'],
            password =  self.data['password1'],
            email = self.data['email'],
        )
        return user

class UserChangeFormCustom(UserChangeForm):
    username = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ('name', 'first_name', 'last_name','email', 'username')

proyecto_final/messages_blog/forms.py
from django import forms

class MessageForms(forms.Form):
    from_message = forms.CharField(max_length=50)
    to = forms.CharField(max_length=50)
    message = forms.CharField(max_length=400)

proyecto_final/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

proyecto_final/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

proyecto_final/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

proyecto_final/templates/blog/account/change_password.html
{% extends 'blog/home.html' %}

{% block title %}
  <title> Change password </title>
{% endblock %}

{% block content %}
<div class="centerInput">
  <h1>Formulario cambio de contraseña</h1>
  <h1>De {{user.username}}</h1>


  <form action="" method="POST">

    {% csrf_token %}
    {{form.as_p}}
      
    <input class="btn btn-primary" type="submit" value="Cambiar contraseña"/>

  </form>
</div>
{% endblock %}

proyecto_final/templates/blog/account/edit_avatar.html
{% extends 'blog/home.html' %}

{% block title %}
  <title> Edit avatar </title>
{% endblock %}

{% block content %}
<div class="centerInput">
  <h1>Formulario edicion de avatar</h1>
  <h1>De {{user.username}}</h1>


  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
      
    {% if form %} 
      <input class="btn btn-primary" type="submit" value="Guardar"/>
    {% endif %}

  </form>
</div>
{% endblock %}

proyecto_final/templates/blog/account/edit_profile.html
{% extends 'blog/home.html' %}

{% block title %}
  <title> Edit profile </title>
{% endblock %}

{% block content %}
<div class="centerInput">
  <h1>Formulario edicion de perfil</h1>
  <h1>De {{user.username}}</h1>


  <form action="" method="POST"> 
    {% csrf_token %}
    {{form.as_p}}
      
    {% if form %} 
      <input class="btn btn-primary" type="submit" value="Guardar"/>
    {% endif %}

  </form>
</div>
{% endblock %}

proyecto_final/templates/blog/account/login.html
{% extends 'blog/home.html' %}

{% block title %}
  <title> Login </title>
{% endblock %}

{% block content %}
<div class="centerInput">
  {% if message %}
    <h1>{{message}}</h1>
  {% endif %}

  <form action="" method="POST"> 
    {% csrf_token %}
    {{form.as_p}}
    
    {% if form %} 
      <input class="btn btn-primary" type="submit" value="Iniciar sesion"/>
    {% endif %}
  </form>
</div>
{% endblock %}

proyecto_final/templates/blog/account/profile.html
{% extends 'blog/home.html' %}

{% block title %}
  <title> Profile </title>
{% endblock %}

{% block content %}
<div class="centerInput">
  <h1>Perfil</h1>
  <h1>De Usuario: {{user.username}}</h1>
  </br>
  <h1>Nombre: {{user.first_name}}</h1>
  <h1>Apellido: {{user.last_name}}</h1>
  <h1>Email: {{user.email}}</h1>
  <a class="btn btn-primary" href= "{% url 'accounts:edit_profile' %}">Editar usuario</a> <a class="btn btn-primary" href= "{% url 'accounts:change_password' %}">Cambiar contraseña</a>
  </br>
  </br>
  </br>
  </br>
  </br>
  <h1>Link: <a href= "{{ link }}"> {{ link }} </a> </h1>
  <h1> Bio: {{ bio }} </h1>
  <img src = "{{profile_image.url}}">
  </br>
  <a class="btn btn-primary" href= "{% url 'accounts:edit_avatar' %}">Editar perfil</a>
  </br>
  </br>
</div>
  
{% endblock %}

proyecto_final/templates/blog/account/signup.html
{% extends 'blog/home.html' %}

{% block title %}
  <title> Signup </title>
{% endblock %}

{% block content %}
<div class="centerInput">
  {% if message %}
    <h1>{{message}}</h1>
  {% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    {% if form %} 
      <input class="btn btn-primary" type="submit" value="Registrarse"/>
    {% endif %}
  </form>
</div>
{% endblock %}